### ISSUE TITLE
Get Hourly Historical Price Data Since Timestamp

### ISSUE THREAD

**Issue by vertangelx** [ttsteiger/cryptocompy#7]
Hello!

Is there a way to get 2000 bars of hourly OHLCV data starting from a given timestamp Currently using `get_historical_data('BTC', 'USD', 'hour')`, not sure how to use the `toTs` feature...

**Comment by rpesche** [comment]
With https://github.com/ttsteiger/cryptocompy/pull/14 you can now use the toTs parameter like this : 

``` python
import datetime

# using a datetime object
get_historical_data('BTC', 'USD', 'hour', toTs=datetime.datetime(2019, 5, 16, 18, 1, 48))
# or using a timestamp directly
get_historical_data('BTC', 'USD', 'hour', toTs=1558022508)
get_historical_data('BTC', 'USD', 'hour', toTs="1558022508")
```
