### ISSUE TITLE
Any chance for a new release?

### ISSUE THREAD

**Issue by sebastianhaberey** [ttsteiger/cryptocompy#9]
Thanks for merging the pull request. I saw that there are a few other changes as well. An updated release would be great :)

**Comment by ttsteiger** [comment]
Hi, Thanks for your comment. A new release will follow in the end of July. Finally have time again to work on this :)!

**Comment by sebastianhaberey** [comment]
Hehe... uni holiday? :+1:

**Comment by sebastianhaberey** [comment]
Hi! I know the feeling of having not enough time, so I'm sorry to bother you again. How much work does it involve to release a new version? If you point me in the right direction I may be able to do it as well...

**Comment by sebastianhaberey** [comment]
Hey @ttsteiger, never mind. I released a maintenance fork of this project as [cryptocompy3 (0.1.2)](https://pypi.org/project/cryptocompy3/), so I'm closing this issue.
